defaults:
  - _self_
  - snow_infos: dev
  - aws_infos: dev

snow_infos:
  account: ${oc.env:SNOWFLAKE_ACCOUNT}
  schema: ${oc.env:SNOWFLAKE_SCHEMA}

aws_infos:
  credentials:
    region_name: ${oc.env:AWS_REGION, eu-west-1}
  
